export const PERMISSIONS = {
  USER_READ: 'USER_READ',
  USER_CREATE: 'USER_CREATE',
  USER_UPDATE: 'USER_UPDATE',
  USER_DELETE: 'USER_DELETE',
  USER_STATUS: 'USER_STATUS',
  USER_ROLE_ASSIGN: 'USER_ROLE_ASSIGN',
  ROLE_READ: 'ROLE_READ',
  ROLE_CREATE: 'ROLE_CREATE',
  ROLE_DELETE: 'ROLE_DELETE',
  ROLE_MANAGE_PERMISSIONS: 'ROLE_MANAGE_PERMISSIONS',
  PERMISSION_READ: 'PERMISSION_READ',
  PERMISSION_CREATE: 'PERMISSION_CREATE',
  PERMISSION_DELETE: 'PERMISSION_DELETE',
  AUDIT_READ: 'AUDIT_READ',
} as const;

export const ROLES = {
  ROLE_ADMIN: 'ROLE_ADMIN',
} as const;
