export const PERMISSIONS = {
  USER_READ: 'USER_READ',
  USER_CREATE: 'USER_CREATE',
  USER_UPDATE: 'USER_UPDATE',
  USER_DELETE: 'USER_DELETE',
  USER_STATUS: 'USER_STATUS',
  USER_ROLE_ASSIGN: 'USER_ROLE_ASSIGN',
  ROLE_READ: 'ROLE_READ',
  ROLE_MANAGE_PERMISSIONS: 'ROLE_MANAGE_PERMISSIONS',
  AUDIT_READ: 'AUDIT_READ',
  // Permissões exclusivas ROLE_DEV (existem no backend via DevRoleBootstrapConfig)
  DEV_ROLE_MANAGE: 'DEV_ROLE_MANAGE',
  DEV_PERMISSION_MANAGE: 'DEV_PERMISSION_MANAGE',
} as const;

export const ROLES = {
  ROLE_ADMIN: 'ROLE_ADMIN',
  ROLE_DEV: 'ROLE_DEV',
} as const;
