/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TotpConfirmRequest } from '../../models/totp-confirm-request';
import { TotpConfirmResponse } from '../../models/totp-confirm-response';

export interface ConfirmTotp$Params {
      body: TotpConfirmRequest
}

export function confirmTotp(http: HttpClient, rootUrl: string, params: ConfirmTotp$Params, context?: HttpContext): Observable<StrictHttpResponse<TotpConfirmResponse>> {
  const rb = new RequestBuilder(rootUrl, confirmTotp.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TotpConfirmResponse>;
    })
  );
}

confirmTotp.PATH = '/auth/2fa/confirm';
