/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TotpSetupResponse } from '../../models/totp-setup-response';

export interface SetupTotp$Params {
}

export function setupTotp(http: HttpClient, rootUrl: string, params?: SetupTotp$Params, context?: HttpContext): Observable<StrictHttpResponse<TotpSetupResponse>> {
  const rb = new RequestBuilder(rootUrl, setupTotp.PATH, 'post');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TotpSetupResponse>;
    })
  );
}

setupTotp.PATH = '/auth/2fa/setup';
