/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PagedAuditLogResponse } from '../../models/paged-audit-log-response';

export interface ListAuditLogs$Params {
  userId?: string;
  action?: string;
  page?: number;
  size?: number;
}

export function listAuditLogs(http: HttpClient, rootUrl: string, params?: ListAuditLogs$Params, context?: HttpContext): Observable<StrictHttpResponse<PagedAuditLogResponse>> {
  const rb = new RequestBuilder(rootUrl, listAuditLogs.PATH, 'get');
  if (params) {
    rb.query('userId', params.userId, {});
    rb.query('action', params.action, {});
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PagedAuditLogResponse>;
    })
  );
}

listAuditLogs.PATH = '/audit-logs';
