/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ApiError {
  errorCode?: string;
  message?: string;
  path?: string;
  timestamp?: string;
  traceId?: string;
}
