/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AuditLogResponse {
  action: string;
  id: number;
  ipAddress: string | null;
  target: string | null;
  timestamp: string;
  who: string;
}
