/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { RoleResponse } from '../models/role-response';
export interface PagedRoleResponse {
  content: Array<RoleResponse>;
  page: number;
  size: number;
  totalElements: number;
  totalPages: number;
}
