/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AuditLogResponse } from '../models/audit-log-response';
export interface PagedAuditLogResponse {
  content: Array<AuditLogResponse>;
  page: number;
  size: number;
  totalElements: number;
  totalPages: number;
}
