/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PermissionResponse } from '../models/permission-response';
export interface PagedPermissionResponse {
  content: Array<PermissionResponse>;
  page: number;
  size: number;
  totalElements: number;
  totalPages: number;
}
