/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SessionInfo {
  createdAt: string;
  expiresAt: string;
  id: number;
  ipAddress: string;
  userAgent: string;
}
