/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface StatsResponse {
  activeUsers: number;
  totalPermissions: number;
  totalRoles: number;
  totalUsers: number;
}
