/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserResponse {
  avatarUrl?: string | null;
  createdAt?: string | null;
  email: string | null;
  emailVerified: boolean;
  enabled: boolean;
  id: number;
  pendingEmail?: string | null;
  permissions: Array<string>;
  roles: Array<string>;
  username: string;
}
